# Generated by Django 4.0.2 on 2022-02-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='title',
            field=models.CharField(default='description', max_length=250, verbose_name='Title'),
        ),
    ]
