# Generated by Django 4.0.2 on 2022-02-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ticket_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Title'),
        ),
    ]
